---
openapi: 3.0.3
info:
  description: PlaceOS Staff-API description
  title: staff-api
  version: 1.2.0
paths:
  /api/staff/v1/surveys:
    get:
      summary: returns a list of surveys
      tags:
        - Surveys
      operationId: Surveys#index
      parameters: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Survey__Responder"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        403:
          description: Forbidden
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        501:
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        406:
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ContentError"
        415:
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ContentError"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ValidationError"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        405:
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
    post:
      summary: creates a new survey
      tags:
        - Surveys
      operationId: Surveys#create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Survey__Responder"
        required: true
      parameters: []
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Survey__Responder"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        403:
          description: Forbidden
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        501:
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        406:
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ContentError"
        415:
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ContentError"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ValidationError"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        405:
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
  /api/staff/v1/surveys/{id}:
    get:
      summary: show a survey
      tags:
        - Surveys
      operationId: Surveys#show
      parameters:
        - name: id
          in: path
          description: the survey id
          example: "..."
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Survey__Responder"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        403:
          description: Forbidden
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        501:
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        406:
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ContentError"
        415:
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ContentError"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ValidationError"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        405:
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
    put:
      summary: patches an existing survey
      tags:
        - Surveys
      operationId: Surveys#update
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Survey__Responder"
        required: true
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: Int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Survey__Responder"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        403:
          description: Forbidden
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        501:
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        406:
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ContentError"
        415:
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ContentError"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ValidationError"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        405:
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
    delete:
      summary: deletes the survey
      tags:
        - Surveys
      operationId: Surveys#destroy
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: Int64
      responses:
        202:
          description: Accepted
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        403:
          description: Forbidden
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        501:
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        406:
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ContentError"
        415:
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ContentError"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ValidationError"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        405:
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
    patch:
      summary: patches an existing survey
      tags:
        - Surveys
      operationId: Surveys#update{2}
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Survey__Responder"
        required: true
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: Int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Survey__Responder"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        403:
          description: Forbidden
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        501:
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        406:
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ContentError"
        415:
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ContentError"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__ValidationError"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
        405:
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application__CommonError"
components:
  schemas:
    JSON__Any:
      type: object
    Survey__Responder:
      type: object
      properties:
        id:
          type: integer
          format: Int64
          nullable: true
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        question_order:
          type: array
          items:
            type: integer
            format: Int64
          nullable: true
    Hash_String__Int32_:
      type: object
      additionalProperties:
        type: integer
        format: Int32
    Application__CommonError:
      type: object
      properties:
        error:
          type: string
        backtrace:
          type: array
          items:
            type: string
          nullable: true
      required:
        - error
      description: generic error feedback, backtraces only provided in development
    Application__ContentError:
      type: object
      properties:
        error:
          type: string
        accepts:
          type: array
          items:
            type: string
          nullable: true
      required:
        - error
      description:
        provides a list of acceptable content types if an unknown one is
        requested
    Application__ParameterError:
      type: object
      properties:
        error:
          type: string
        parameter:
          type: string
          nullable: true
        restriction:
          type: string
          nullable: true
      required:
        - error
      description: Provides details on which parameter is missing or invalid
    Application__ValidationError:
      type: object
      properties:
        error:
          type: string
        failures:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                nullable: true
              reason:
                type: string
            required:
              - reason
      required:
        - error
        - failures
  responses: {}
  headers: {}
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
